server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location = /subscription/success {
        try_files /subscription/success/index.html =404;
    }

    location = /subscription/cancel {
        try_files /subscription/cancel/index.html =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
